In [ ]:
# %load_ext autoreload
%autoreload 2

import numpy as np
import scipy as sc
import torch
from cink import loss_fn

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [64]:
a(5)

10

np.float32(0.0)

In [7]:
embs = torch.load('/home/kgbman/recsys/ml20m/item_embs.pt')

In [11]:
embs.shape

torch.Size([17691, 200])

In [80]:
class valDataset(torch.utils.data.Dataset):
    def __init__(self, user_emb, item_emb, item_bias, scores, valin_scores):
        self.users = torch.load(user_emb)
        self.items = torch.load(item_emb)
        self.bias = torch.load(item_bias)
        matrix = sc.sparse.load_npz(scores)
        self.scores = matrix
        matrix = sc.sparse.load_npz(valin_scores)
        self.valin_scores = self.get_nonzeros(matrix)
        
    def __len__(self):
        return len(self.scores)
    
    @staticmethod
    def get_nonzeros(data):
        return [data[i].indices.tolist() for i in range(data.shape[0])]
    
    def __getitem__(self, idx):
        user = self.users[idx]
        
        i_scores = user @ self.items.T + self.bias
        non_zeros = self.valin_scores[idx]
        
        i_scores[non_zeros] = - 1e10
        sorted_items = torch.sort(i_scores, dim=-1, descending=True)[-1][:100].tolist()
        socres_from_ranker = torch.sort(i_scores, dim=-1, descending=True)[0][:100].tolist()
        
        item_embs = self.items[sorted_items]
        real_scores = torch.tensor(self.scores[idx, sorted_items].toarray())
        print(user.shape, item_embs.shape)
        zeros = torch.zeros_like(item_embs)
        zeros[torch.arange(100), :] = user
        return torch.cat([zeros, item_embs], dim=-1), real_scores, torch.tensor(socres_from_ranker)


In [81]:
data = valDataset(
    user_emb='/home/kgbman/recsys/ml20m/user_embs_mu_valid_in.pt',
    item_emb='/home/kgbman/recsys/ml20m/item_embs.pt',
    item_bias='/home/kgbman/recsys/ml20m/item_bias.pt',
    scores='/home/kgbman/recsys/ml20m/data_valid_out.npz',
    valin_scores='/home/kgbman/recsys/ml20m/data_valid_in.npz'
)

In [82]:
data[2]

torch.Size([200]) torch.Size([100, 200])


(tensor([[ 0.2546, -0.1474,  0.6034,  ..., -0.1277,  0.2437, -0.0594],
         [ 0.2546, -0.1474,  0.6034,  ...,  0.1427,  0.1705, -0.0582],
         [ 0.2546, -0.1474,  0.6034,  ...,  0.0460,  0.0543, -0.1684],
         ...,
         [ 0.2546, -0.1474,  0.6034,  ...,  0.0175,  0.0921,  0.0357],
         [ 0.2546, -0.1474,  0.6034,  ...,  0.2602,  0.1101,  0.0547],
         [ 0.2546, -0.1474,  0.6034,  ...,  0.1560,  0.3515, -0.1266]]),
 tensor([[1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
          0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
          0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
          0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
          1., 1., 0., 0., 0., 0., 1., 0., 0., 0.]]),
 tensor([5.2332, 4.8276, 4.7200, 4.6747, 4.6718, 4.6683, 4.5695, 4.5419, 4.5124,
         4.489

In [50]:
data = sc.sparse.load_npz('/home/kgbman/recsys/ml20m/data_valid_out.npz')

In [57]:
def loss(b):
    return b

In [58]:
loss = loss(10)

In [ ]:
loss = loss(10)